[package]
name = "ytx-initdb"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
postgres = "0.19"
url="2.5"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde_json = "1.0.142"
anyhow = "1.0.98"
unicode-xid = "0.2.6"
